export const products = [
    {
        id: "7",
        brand: "Shein",
        name: "Tropical Print Chain Detail Asymmetrical Neck",
        price: "16.00",
        size: ["XS", "S", "M", "L", "XL"],
        description: "SHEIN VCAY features all your must-pack fashion essentials for a complete vacation style.",
        images: [
            "shein-a1.jpg",
            "shein-a2.jpg",
            "shein-a3.jpg",
        ],
        gender:"women",
        color: "green",
        category: "casual",
        discount: 10,
        stock: 50,
    },
    {
        id: "1",
        brand: "Shein",
        name: "3pcs Breathable Sports Set",
        price: "22.76",
        size: ["XS", "S", "M", "L", "XL"],
        description: "Army Green Long Sleeve Plain Leggings High Stretch Women Sports Sets, size features are:Bust: ,Length: ,Sleeve Length:Long Sleeve",
        images: [
            "shein-1.jpg",
            "shein-2.jpg",
            "shein-3.jpg",
        ],
        gender:"women",
        color: "green",
        category: "sports",
        discount: 0,
        stock: 100,
    },
    {
        id: "2",
        brand: "Gymshark",
        name: "SWEAT SEAMLESS MIDI TANK",
        price: "36.00",
        size: ["XS", "S", "M", "L", "XL"],
        description: "Your sweat speaks for itself, so now it’s time to embrace it. Sleek, soft and comfortable fabrics meet powerful and resilient designs in the new SWEAT collection. DYNMC™️ fabric (powered by Sensil Nylon 66) heightens breathability whilst still providing maximum durability, so you can stay cool during the sweatiest sessions, and rely on SWEAT to endure your workouts time and time again. In the collection that you’ll feel hyped to wear for your next workout, all that’s left to do is sweat.",
        images: [
            "gymshark-1.jpg",
            "gymshark-2.jpg",
            "gymshark-3.jpg",
        ],
        gender:"women",
        color: "gray",
        category: "sports",
        discount: 0,
        stock: 100,
    },
    {
        id: "3",
        brand: "Gymshark",
        name: "SWEAT SEAMLESS MIDI TANK (Green)",
        price: "36.00",
        size: ["XS", "S", "M", "L", "XL"],
        description: "Your sweat speaks for itself, so now it’s time to embrace it. Sleek, soft and comfortable fabrics meet powerful and resilient designs in the new SWEAT collection. DYNMC™️ fabric (powered by Sensil Nylon 66) heightens breathability whilst still providing maximum durability, so you can stay cool during the sweatiest sessions, and rely on SWEAT to endure your workouts time and time again. In the collection that you’ll feel hyped to wear for your next workout, all that’s left to do is sweat.",
        images: [
            "SweatSeamlessMidiTank-green-1.jpg",
            "SweatSeamlessMidiTank-green-2.jpg",
            "SweatSeamlessMidiTank-green-3.jpg",
        ],
        gender:"women",
        color: "teal",
        category: "sports",
        discount: 0,
        stock: 100,
    },
    {
        id: "4",
        brand: "Gymshark",
        name: "ADAPT CAMO SEAMLESS LACE UP BACK TOP",
        price: "46.00",
        size: ["XS", "S", "M", "L", "XL"],
        description: "It’s time to complete your latest workout mission in Adapt Camo. A refreshed camo jacquard meets our signature seamless fabric to create your perfect training partner. And with plenty of styles, versatile colours, and sweat-wicking tech to keep you cool and dry, Adapt Camo’s here to help you reach your best.",
        images: [
            "AdaptCamoSeamlessLaceBack-1.jpg",
            "AdaptCamoSeamlessLaceBack-2.jpg",
            "AdaptCamoSeamlessLaceBack-3.jpg",
        ],
        gender:"women",
        color: "green",
        category: "sports",
        discount: 0,
        stock: 100,
    },
    {
        id: "5",
        brand: "Gymshark",
        name: "ADAPT CAMO SEAMLESS LACE UP BACK TOP",
        price: "46.00",
        size: ["XS", "S", "M", "L", "XL"],
        description: "It’s time to complete your latest workout mission in Adapt Camo. A refreshed camo jacquard meets our signature seamless fabric to create your perfect training partner. And with plenty of styles, versatile colours, and sweat-wicking tech to keep you cool and dry, Adapt Camo’s here to help you reach your best.",
        images: [
            "AdaptCamoSeamlessLaceBack-W1.jpg",
            "AdaptCamoSeamlessLaceBack-W2.jpg",
            "AdaptCamoSeamlessLaceBack-W3.jpg",
        ],
        gender:"women",
        color: "white",
        category: "sports",
        discount: 0,
        stock: 100,
    },
    {
        id: "6",
        brand: "Gymshark",
        name: "ADAPT ANIMAL SEAMLESS LACE UP BACK TOP",
        price: "30.00",
        size: ["XS", "S", "M", "L", "XL"],
        description: "The collection made for lifting, unleash your wild side in Adapt Animal. Sweat-wicking fabric, seamless stretch and zero-distraction designs let you lift in comfort and support every day, in every way..",
        images: [
            "VitalSeamlessHighNeckLsCropTopStellarBlue-1.jpg",
            "VitalSeamlessHighNeckLsCropTopStellarBlue-2.jpg",
            "VitalSeamlessHighNeckLsCropTopStellarBlue-3.jpg",
        ],
        gender:"women",
        color: "white",
        category: "sports",
        discount: 0,
        stock: 100,
    },
];